version: '3'
services:
  s1: 
    build: ./service1/
    ports:
      - 3000:3000
  s2: 
    build: ./service2/
    ports:
      - 3001:3001
  s3: 
    build: ./service3/
    ports:
      - 3002:3002
  gateway:
    image: nginx
    volumes:
      - ./Gateway/api.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80